spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://127.0.0.1:3306/WhoDoDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
    username: root
    password: jwjw0185**

  jpa:
    hibernate:
      #?? create, update, none, create-drop, validate ??
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        user_sql_comments: true

  profiles:
    include: jwt

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug
      hibernate:
        SQL: debug

    boardexample:
      myboard: info

  jwt:
    header: Authorization
    secret: {and0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdp}
    token-validity-in-seconds: 86400

  redis:
    host: localhost
    port: 6379